NETWORK_INTERFACE:wlo1
PASSWORD:790321
PACKETS_OUTPUT_DIRNAME:${HOME}/TFG/archivos
PACKETS_OUTPUT_FILENAME:paquetes
TIME_SECONDS:10
TIME_MINUTES:0.25
FILEBEAT_PATH:${HOME}/filebeat-7.4.2-linux-x86_64
ELASTICSEARCH_PATH:${HOME}/elasticsearch-7.3.2
NODES_NUMBER:3
NODE_TIMEOUT:5.0
